from osbot.api.API_GS_Bot import API_GS_Bot


class Lambda_Handler:

    def run(self,data):
        if "challenge" in data:              # required for Slack event check
            return data.get("challenge")
        team_id = data.get('team_id')
        if data.get('event'):
            slack_event = data.get('event')
            if ("bot_id" in slack_event) is False:                      # this happens when the data was generated by an bot
                slack_event['team_id'] = team_id                        # add team_id field so that it is available in the other lambda handlers
                result = API_GS_Bot(team_id).process_event(slack_event)          # add a `return` here to see message in test
        elif data.get('body'):
            result = API_GS_Bot(team_id).process_posted_body(data.get('body'))

        if team_id is None:                                             # to help with unit tests
            return result
        return "200 OK"
